const testData = [
  { media_id : 23,
    title : 'Titanic',
    media_type : 'movie',
    keywords : null,
    avg_rating : 9.5,
    image_url : 'http://www.impawards.com/1997/posters/titanic_ver2.jpg',
    revenue : 100000000,
    overview : null,
    runtime : 7254,
    rating_count : 14053,
    language : 'en',
    release_date : 'November 18, 1997',
  },
  { media_id : 254,
    title : 'Avatar',
    media_type : 'movie',
    keywords : null,
    avg_rating : 9.1,
    image_url : 'http://www.impawards.com/2009/posters/avatar.jpg',
    revenue : 1345000000,
    overview : null,
    runtime : 9224,
    rating_count : 74403,
    language : 'en',
    release_date : 'December 10, 2009',
  },
  { media_id : 1254,
    title : 'Gone with the Wind',
    media_type : 'book',
    keywords : null,
    avg_rating : 9.6,
    image_url : 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1551144577l/18405._SY475_.jpg',
    authors : 'Margaret Mitchell',
    description : "Scarlett O'Hara, the beautiful, spoiled daughter of a well-to-do Georgia plantation owner, must use every means at her disposal to claw her way out of the poverty she finds herself in after Sherman's March to the Sea.",
    pages : 1037,
    rating_count : 74403,
    review_count : 1042253,
  }
]